version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 8086:80
    volumes:
      - ../:/var/www:ro
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpserver

  phpserver:
    image: php:8.3-fpm
    working_dir: /var/www/
    volumes:
      - ../:/var/www/
